/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ContractsContractIdRouteImport } from './routes/contracts.$contractId'
import { Route as ContractsNewRouteImport } from './routes/contracts.new'
import { Route as DisputesDisputeIdRouteImport } from './routes/disputes.$disputeId'
import { Route as ProfileHandleRouteImport } from './routes/profile.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsContractIdRoute = ContractsContractIdRouteImport.update({
  id: '/contracts/$contractId',
  path: '/contracts/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsNewRoute = ContractsNewRouteImport.update({
  id: '/contracts/new',
  path: '/contracts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesDisputeIdRoute = DisputesDisputeIdRouteImport.update({
  id: '/disputes/$disputeId',
  path: '/disputes/$disputeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHandleRoute = ProfileHandleRouteImport.update({
  id: '/profile/$handle',
  path: '/profile/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/contracts/new': typeof ContractsNewRoute
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/profile/$handle': typeof ProfileHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/contracts/new': typeof ContractsNewRoute
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/profile/$handle': typeof ProfileHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/contracts/new': typeof ContractsNewRoute
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/profile/$handle': typeof ProfileHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/verify'
    | '/wallet'
    | '/contracts/$contractId'
    | '/contracts/new'
    | '/disputes/$disputeId'
    | '/profile/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/verify'
    | '/wallet'
    | '/contracts/$contractId'
    | '/contracts/new'
    | '/disputes/$disputeId'
    | '/profile/$handle'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/verify'
    | '/wallet'
    | '/contracts/$contractId'
    | '/contracts/new'
    | '/disputes/$disputeId'
    | '/profile/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  VerifyRoute: typeof VerifyRoute
  WalletRoute: typeof WalletRoute
  ContractsContractIdRoute: typeof ContractsContractIdRoute
  ContractsNewRoute: typeof ContractsNewRoute
  DisputesDisputeIdRoute: typeof DisputesDisputeIdRoute
  ProfileHandleRoute: typeof ProfileHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$contractId': {
      id: '/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof ContractsContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/new': {
      id: '/contracts/new'
      path: '/contracts/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof ContractsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes/$disputeId': {
      id: '/disputes/$disputeId'
      path: '/disputes/$disputeId'
      fullPath: '/disputes/$disputeId'
      preLoaderRoute: typeof DisputesDisputeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$handle': {
      id: '/profile/$handle'
      path: '/profile/$handle'
      fullPath: '/profile/$handle'
      preLoaderRoute: typeof ProfileHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  VerifyRoute: VerifyRoute,
  WalletRoute: WalletRoute,
  ContractsContractIdRoute: ContractsContractIdRoute,
  ContractsNewRoute: ContractsNewRoute,
  DisputesDisputeIdRoute: DisputesDisputeIdRoute,
  ProfileHandleRoute: ProfileHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
