[build]
buildCommand = "composer update --no-dev --optimize-autoloader --no-interaction --no-scripts --prefer-stable && composer dump-autoload --optimize && php artisan package:discover --ansi || true && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/up"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
